export const ESTADOS = new Map();
ESTADOS.set('Acre', 'AC');
ESTADOS.set('Alagoas', 'AL');
ESTADOS.set('Amapá', 'AP');
ESTADOS.set('Amazonas', 'AM');
ESTADOS.set('Bahia', 'BA');
ESTADOS.set('Ceará', 'CE');
ESTADOS.set('Distrito Federal', 'DF');
ESTADOS.set('Espírito Santo', 'ES');
ESTADOS.set('Goiás', 'GO');
ESTADOS.set('Maranhão', 'MA');
ESTADOS.set('Mato Grosso', 'MT');
ESTADOS.set('Mato Grosso do Sul', 'MS');
ESTADOS.set('Minas Gerais', 'MG');
ESTADOS.set('Pará', 'PA');
ESTADOS.set('Paraíba', 'PB');
ESTADOS.set('Paraná', 'PR');
ESTADOS.set('Pernambuco', 'PE');
ESTADOS.set('Piauí', 'PI');
ESTADOS.set('Rio de Janeiro', 'RJ');
ESTADOS.set('Rio Grande do Norte', 'RN');
ESTADOS.set('Rio Grande do Sul', 'RS');
ESTADOS.set('Rondônia', 'RO');
ESTADOS.set('Roraima', 'RR');
ESTADOS.set('Santa Catarina', 'SC');
ESTADOS.set('São Paulo', 'SP');
ESTADOS.set('Sergipe', 'SE');
ESTADOS.set('Tocantins', 'TO');
